os:
  # editPreset: 'helix'
  edit: '~/.cargo/bin/hx -- {{filename}}'
  editAtLine: "~/.cargo/bin/hx -- {{filename}}:{{line}}"
  editAtLineAndWait: "~/.cargo/bin/hx -- {{filename}}:{{line}}"
  editInTerminal: true 

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default    
    selectedLineBgColor:
      - '#382c6d'
    selectedRangeBgColor:
      - '#382c6d'
