#!/usr/bin/env bash

# +--------+
# | System |
# +--------+

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'
alias reload='source $HOME/.zshenv && source ${ZDOTDIR:-$HOME}/.zshrc'

# +-----+
# | Zsh |
# +-----+

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index} > /dev/null"; unset index # directory stack

alias ~='cd $HOME'
alias '\-'='cd -'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias _='sudo '

# +---------+
# | Chezmoi |
# +---------+

alias cm="chezmoi"
alias cma="chezmoi add"
alias cmd="chezmoi diff"
alias cmf="chezmoi forget"
alias cmr="chezmoi re-add"
alias cms="chezmoi status"

# +-----------------+
# | Flutter and Dart|
# +-----------------+

alias fl="flutter"
alias flattach="flutter attach"
alias flb="flutter build"
alias flbr="flutter pub run build_runner build --delete-conflicting-outputs"
alias flchnl="flutter channel"
alias flc="flutter clean"
alias fldvcs="flutter devices"
alias fldoc="flutter doctor"
alias flpub="flutter pub"
alias flget="flutter pub get"
alias flr="flutter run"
alias flrd="flutter run --debug"
alias flrp="flutter run --profile"
alias flrr="flutter run --release"
alias flupgrd="flutter upgrade"

# +--------+
# | git    |
# +--------+

alias gs="git status"

# +--------+
# | helix  |
# +--------+

alias hi="hx-layout.sh"
alias hx=/Users/adrian/.cargo/bin/hx

# +----------+
# | Homebrew |
# +----------+

alias bbd="brew bundle dump"

# +---------+
# | Lazygit |
# +---------+

alias lg="lazygit"

# +--------+
# | lf     |
# +--------+

alias lf="lfcd"

# +--------+
# | ls/exa |
# +--------+

alias l="exa -a --icons --long"
alias lt="exa -a --icons --long -T"

# +---------------+
# | NVIM Switcher |
# +---------------+

alias nvim-lazy="NVIM_APPNAME=LazyVim nvim"
alias kvim="NVIM_APPNAME=kickstart nvim"
alias cvim="NVIM_APPNAME=NvChad nvim"
alias avim="NVIM_APPNAME=AstroNvim nvim"

# +----------+
# | Personal |
# +----------+

# Folders
alias doc="$HOME/Documents"
alias dow="$HOME/Downloads"
alias dot="$HOME/.dotfiles"
