# taps
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "xz"
brew "openssl@3"
brew "harfbuzz"
brew "libzip"
brew "readline"
brew "node"
brew "zlib"

# Video and Image utils
brew "ffmpeg"
brew "aom"
brew "openjpeg"
brew "leptonica"
brew "tesseract"
brew "jpeg-xl"
brew "webp"

# Books
cask "calibre"
cask "kindle"
cask "sigil"
cask "vitalsource-bookshelf"
# ade needs a password so install manually
cask "adobe-digital-editions"

# Go
brew "boost"
brew "katago"
cask "katrain"
mas 'SmartGo One', id: 1465746992

# Binaries
cask "alfred"
cask "anki"
mas "bitwarden", id: 1352778147
cask "drawio"
cask "clickup"
cask "cleanmymac"
# brew "mackup"
brew "mas"
cask "microsoft-word"
cask "microsoft-excel"
brew  "saulpw/vd/visidata"

# Terminal and shell
brew "btop"
brew "exa"
brew "fd"
brew "fzf"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "ripgrep"
brew "sd"
brew "tldr"
brew "trash-cli"
cask "wezterm"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-vi-mode"

# lf and preview
brew "lf"
brew "jq"
brew "poppler"
brew "w3m"

# Editor
brew "helix"
brew "kakoune"
brew "neovim"
cask "obsidian"
cask "visual-studio-code"

# Coding Social
cask "element"

# Browser, http etc.
cask "arc"
cask "firefox"
cask "google-chrome"
cask "radarr"
cask "sabnzbd"
cask "sonarr"
brew "wget"

# Development
cask "db-browser-for-sqlite"
cask "flutter"
brew "go"
cask "gpg-suite"
brew "hugo"
brew "perl"
brew "pipx"
brew "pyenv"
brew "rustup"
brew "sqlite"
mas "Xcode", id: 497799835

# Language Support
brew "gopls"
brew "lua-language-server"
brew "marksman"
brew "python-lsp-server"
brew "taplo"
brew "vscode-langservers-extracted"
brew "yaml-language-server"

# Source Code Management
brew "chezmoi"
brew "delta"
brew "gh"
brew "lazygit"

# Fonts
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"

cask "hammerspoon"
cask "hyperkey"
cask "maccy"

# Utilities
mas 'Color Picker', id: 1545870783
brew 'bat'

vscode "aaron-bond.better-comments"
vscode "ahmadawais.shades-of-purple"
vscode "alefragnani.rtf"
vscode "asvetliakov.vscode-neovim"
vscode "bhughes339.replacerules"
vscode "circlecodesolution.ccs-flutter-color"
vscode "darkriszty.markdown-table-prettify"
vscode "Dart-Code.dart-code"
vscode "Dart-Code.flutter"
vscode "devmuaz.flutterhookssnippets"
vscode "donjayamanne.githistory"
vscode "DotJoshJohnson.xml"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "GitHub.copilot"
vscode "Gruntfuggly.todo-tree"
vscode "hirantha.json-to-dart"
vscode "hzgood.dart-data-class-generator"
vscode "janisdd.vscode-edit-csv"
vscode "joekon.ssmacro"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.autopep8"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "Nash.awesome-flutter-snippets"
vscode "PKief.material-icon-theme"
vscode "plibither8.remove-comments"
vscode "redhat.vscode-xml"
vscode "robert-brunhage.flutter-riverpod-snippets"
vscode "TakumiI.markdowntable"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"
vscode "ZainChen.json"
